FROM node:18

WORKDIR /app

# ติดตั้ง dependency
COPY package.json package-lock.json ./
RUN npm install

# คัดลอกโค้ดและสคริปต์ทั้งหมด
COPY . .

# ติดตั้ง cron
RUN apt-get update && apt-get install -y cron

# คัดลอกไฟล์ crontab เข้า container
COPY crontab.txt /etc/cron.d/cleanjob

# ตั้ง permission และลง crontab
RUN chmod 0644 /etc/cron.d/cleanjob && crontab /etc/cron.d/cleanjob

# ตั้ง permission ให้ start.sh
RUN chmod +x ./start.sh

# เปิดพอร์ต 3000
EXPOSE 3000

# สั่งรันสคริปต์
CMD ["./start.sh"]
