version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql-db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      NODE_ENV: production
    volumes: [] 