import type { Metadata } from "next";
import {  Kanit } from "next/font/google";
import "./globals.css";
import AppLayoutClient from "./components/ui/AppLayoutClient";
import { StudentFilterProvider } from '@/context/StudentFilterContext/page';



const kanit = Kanit({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-kanit", // ใช้ร่วมกับ Tailwind ได้
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${kanit.variable} antialiased bg-[#EFEFEF] flex min-h-screen`}
      >
        <StudentFilterProvider>
        <AppLayoutClient>{children}</AppLayoutClient>
        </StudentFilterProvider>
      </body>
    </html>
  )
}

