import type { Metadata } from "next";
import { Geist, Geist_Mono, Kanit } from "next/font/google";
import "./globals.css";
import AppLayoutClient from "./components/ui/AppLayoutClient";
import SideNavbar from "./components/ui/SideNavbar";


const kanit = Kanit({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-kanit", // ใช้ร่วมกับ Tailwind ได้
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],

});


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`${kanit.variable} antialiased bg-[#EFEFEF] flex min-h-screen`}
      >
        <AppLayoutClient>{children}</AppLayoutClient>
      </body>
    </html>
  )
}

