import type { Metadata } from "next"
import { Geist, Geist_Mono, Kanit } from "next/font/google"
import "../globals.css"

const kanit = Kanit({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-kanit", 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
          <body
            className={`${kanit.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-[#EFEFEF] min-h-screen flex`}
          >
            {children}
          </body>
        </html>
  )
}
