CREATE USER 'devuser1'@'%' IDENTIFIED BY 'password1';
GRANT ALL PRIVILEGES ON *.* TO 'devuser1'@'%' WITH GRANT OPTION;

CREATE USER 'devuser2'@'%' IDENTIFIED BY 'password2';
GRANT ALL PRIVILEGES ON *.* TO 'devuser2'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
